#!/bin/bash

set -eou pipefail

docker \
  run \
  -t \
  -v "${PWD}/data:/data" \
  ghcr.io/project-osrm/osrm-backend \
  osrm-extract \
  -p /opt/car.lua \
  /data/county-36001_new-york-240101.osm.pbf \
  || echo "osrm-extract failed"

docker \
  run \
  -t \
  -v "${PWD}/data:/data" \
  ghcr.io/project-osrm/osrm-backend \
  osrm-contract \
  /data/county-36001_new-york-240101.osm.pbf \
  || echo "osrm-extract failed"
