#!/bin/bash

set -euo pipefail

GDB=./initial_data/tlgdb_2022_a_36_ny.gdb

OUTDIR=./census_tract_geojson

mkdir -p $OUTDIR

ogr2ogr -lco STRING_QUOTING=IF_NEEDED -F CSV /vsistdout/ -sql "SELECT GEOID FROM Census_Tract" $GDB \
  | tail -n +2 \
  | sort \
  | while IFS= read -r geoid
  do
    echo $geoid
    
    ogr2ogr \
      -F GeoJSONSeq \
      /vsistdout/ \
      -where "GEOID = '$geoid'" \
      $GDB \
      Census_Tract \
    | gzip \
    > "$OUTDIR/census-tract-$geoid.geojson.gz"
  done

